const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('assert'),fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const checks=[];const ok=n=>{checks.push(n);console.log('PASS',n)};try{
 const p=await b.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(30000);
 await p.goto('http://127.0.0.1:18080/#work/decision');
 const f=p.frameLocator('.project-frames .frame-shell[data-service="solver"] iframe');
 await f.locator('#loadExample').click();await f.locator('[data-view="modelView"]').click();
 const model=JSON.parse(await f.locator('#modelEditor').inputValue());model.objective.constant=123;
 await f.locator('#modelEditor').fill(JSON.stringify(model));
 let requested;const started=new Promise(r=>requested=r);
 await p.route('**/api/model/normalize',async route=>{requested();await new Promise(r=>setTimeout(r,700));await route.continue()});
 await f.locator('#solveBtn').click();await started;
 model.objective.constant=456;await f.locator('#modelEditor').fill(JSON.stringify(model));
 await f.getByText('模型在校验期间已修改，请重新应用或求解。',{exact:true}).waitFor();
 assert.equal(JSON.parse(await f.locator('#modelEditor').inputValue()).objective.constant,456);
 await p.unroute('**/api/model/normalize');ok('Delayed normalization cannot overwrite newer input');
 await f.locator('#loadExample').click(); await f.locator('[data-view="modelView"]').click();
 const next=JSON.parse(await f.locator('#modelEditor').inputValue()); next.objective.constant=99;
 await f.locator('#modelEditor').fill(JSON.stringify(next));
 let validating;const validationStarted=new Promise(r=>validating=r);
 await p.route('**/api/model/validate',async route=>{validating();await new Promise(r=>setTimeout(r,700));await route.continue()});
 await f.locator('#solveBtn').click();await validationStarted;
 next.objective.constant=999;await f.locator('#modelEditor').fill(JSON.stringify(next));
 await f.getByText('模型在校验期间已修改，请重新应用或求解。',{exact:true}).waitFor();
 assert.equal(JSON.parse(await f.locator('#modelEditor').inputValue()).objective.constant,999);
 await p.unroute('**/api/model/validate');ok('Editing during validation cannot start a solve with the previous model');
 await f.locator('#loadExample').click();await f.locator('#solveBtn').click();await f.getByText('目标值 2360',{exact:true}).waitFor();
 await p.locator('.skip-link').focus();await p.keyboard.press('Enter');
 assert(p.url().endsWith('#work/decision'));assert.equal(await p.evaluate(()=>document.activeElement.id),'main-content');ok('Keyboard skip link focuses content without changing route');
 const rail=p.locator('.step-rail');await rail.locator('[data-complete]').focus();await p.keyboard.press('Enter');
 assert.equal(await p.evaluate(()=>document.activeElement.dataset.complete),'decision');ok('Manual step navigation retains keyboard focus');
 await p.setViewportSize({width:390,height:844});await p.locator('.project-frames').scrollIntoViewIfNeeded();
 const skip=await p.locator('.skip-link').boundingBox();assert(skip.x<0);ok('Skip link remains offscreen while scrolling until focused');
 const molecular=await b.newPage({viewport:{width:1440,height:1000}});molecular.setDefaultTimeout(45000);
 await molecular.goto('http://127.0.0.1:18080/#work/molecular');
 const mf=molecular.frameLocator('.project-frames .frame-shell[data-service="molecular"] iframe');
 await mf.getByRole('button',{name:'计算 GPC 分子量',exact:true}).click();await mf.getByText('55,000.00',{exact:true}).waitFor();
 const value=mf.getByText('55,000.00',{exact:true});
 assert(await value.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'GPC Mw should not be ellipsized');
 await molecular.screenshot({path:'runtime/agent-molecular-work.png',fullPage:true});ok('Fresh direct molecular workspace link supports actual GPC computation');
 await molecular.close();
 fs.writeFileSync('runtime/agent-edge-verification.json',JSON.stringify({checked_at:new Date().toISOString(),passed:checks},null,2));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
